# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  tpImplicite_config = debug
endif
ifeq ($(config),release)
  tpImplicite_config = release
endif

PROJECTS := tpImplicite

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

tpImplicite:
ifneq (,$(tpImplicite_config))
	@echo "==== Building tpImplicite ($(tpImplicite_config)) ===="
	@${MAKE} --no-print-directory -C . -f tpImplicite.make config=$(tpImplicite_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f tpImplicite.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   tpImplicite"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"